### ISSUE TITLE
Barra de rolagem nos títulos

### ISSUE THREAD

**Issue by SampaioFelipe** [marcelodeolive1ra/sitepetbcc#5]
![screenshot from 2016-10-15 16-21-44](https://cloud.githubusercontent.com/assets/17321719/19412787/94e380e8-92f3-11e6-9fe0-e297768fec59.png)
Ao lado do cabeçalho de títulos está aparecendo uma barra de rolagem no canto direito (onde estou com o mouse na foto)

**Comment by SampaioFelipe** [comment]
Opa, não dá pra ver meu mouse (kkkk). Mas é aquela parte escura ali.

**Comment by marcelodeolive1ra** [comment]
Nas demais páginas também? E só no Firefox? Eu tinha corrigido isso no commit 29ec022. 😭

**Comment by SampaioFelipe** [comment]
Em todas as páginas, menos na home (pq não tem esse titulo kkk)
Só tenho o firefox no ubuntu, vou instalar o chrome e te respondo.

**Comment by marcelodeolive1ra** [comment]
Oh, no!
Ainda pior no Chrome no Windows 10:

![capturar](https://cloud.githubusercontent.com/assets/13210266/19412903/3101666e-92f6-11e6-9a53-7519002a2292.PNG)

**Comment by marcelodeolive1ra** [comment]
Removi o padding em `#titulo_pagina`. Corrigiu no Chrome no Windows 10 e no Safari no Mac também (no Safari não mostrava a barra de rolagem, mas era possível rolar apenas na área do título).

**Comment by SampaioFelipe** [comment]
Aqui no firefox funcionou também
